'use strict';
const $=id=>document.getElementById(id);
const money=n=>'$'+Number(n||0).toFixed(2);
const now=()=>Date.now();
const safe=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const DEFAULTS={backendUrl:'https://rolling-wrench-ai-backend.onrender.com',supabaseUrl:'https://uxpkqwcmvtqvubibbrek.supabase.co',supabaseKey:'sb_publishable_MIwgVQm6UPIbd76uIm2-tw_NzSw19ym',theme:'green',bgStyle:'carbon',laborRate:135,serviceCall:250,tax:7,shopName:'Rolling Wrench Diesel',owner:'James Jacobs',phone:'260-502-6222',website:'www.rollingwrenchdiesel.com'};
const LS={get(k,d){try{return JSON.parse(localStorage.getItem(k))??d}catch{return d}},set(k,v){localStorage.setItem(k,JSON.stringify(v))}};
let current='home', historyStack=[];
let activeClock=LS.get('activeClock','A');
let timer=null;
const localParts=[
 {q:'x15 water pump isx',name:'Cummins X15 / ISX Water Pump',num:'4376357',group:'Cooling',notes:'Verify ESN/CPL. Common add-ons: coolant, belt, thermostat, gasket.',job:'water pump',price:0},
 {q:'isx nox sensor',name:'Cummins ISX NOx Sensor',num:'4309129',group:'Emissions',notes:'Verify inlet/outlet position by VIN/ESN.',price:0},
 {q:'dd15 water pump',name:'Detroit DD15 Water Pump',num:'A4722001601',group:'Cooling',notes:'Verify engine serial. Inspect belt/tensioner/coolant.',price:0},
 {q:'mx13 turbo actuator paccar',name:'PACCAR MX-13 Turbo Actuator',num:'1931652',group:'Air',notes:'Calibrate after install. Verify turbo condition first.',price:0},
 {q:'maxxforce egr valve',name:'MaxxForce 13 EGR Valve',num:'1876105C95',group:'Emissions',notes:'Verify failure with commanded test before replacing.',price:0},
 {q:'brake job 4707 shoes drums hardware wheel seal hub oil',name:'Brake Job Smart Kit',num:'4707 / 16.5x7',group:'Brakes',notes:'Shoes, drums if worn, hardware kit, wheel seals, hub oil. Confirm axle and brake size.',job:'brake job',price:0},
 {q:'clutch job eaton fuller clutch pilot bearing rear main seal',name:'Heavy Truck Clutch Job Smart Kit',num:'VIN VERIFY',group:'Drivetrain',notes:'Clutch, pilot bearing, rear main inspection, trans fluid, clutch brake, flywheel resurfacing.',job:'clutch',price:0}
];
function settings(){return {...DEFAULTS,...LS.get('settings',{})}}
function toast(msg){const t=document.createElement('div');t.className='toast';t.textContent=msg;document.body.appendChild(t);setTimeout(()=>t.remove(),3800)}
function show(id){if(!$(id))return; if(current&&current!==id)historyStack.push(current); current=id; document.querySelectorAll('.screen').forEach(s=>s.classList.remove('active')); $(id).classList.add('active'); window.scrollTo({top:0,behavior:'smooth'}); renderAll();}
function goBack(){const last=historyStack.pop(); if(last){current=last;document.querySelectorAll('.screen').forEach(s=>s.classList.remove('active'));$(last)?.classList.add('active');window.scrollTo({top:0,behavior:'smooth'});}else show('home');}
async function supabaseReq(table,method='GET',body=null,query=''){const s=settings(); if(!s.supabaseUrl||!s.supabaseKey)throw new Error('Missing Supabase settings'); const url=s.supabaseUrl.replace(/\/$/,'')+`/rest/v1/${table}${query}`; const headers={apikey:s.supabaseKey,Authorization:'Bearer '+s.supabaseKey,'Content-Type':'application/json',Prefer:'return=representation'}; const res=await fetch(url,{method,headers,body:body?JSON.stringify(body):null}); const data=await res.json().catch(()=>null); if(!res.ok)throw new Error((data&&JSON.stringify(data))||res.statusText); return data;}
async function saveRow(table,obj){try{return await supabaseReq(table,'POST',obj)}catch(e){console.warn('Supabase save failed',table,e.message);throw e}}
function activeTruck(){return LS.get('activeTruck',{})} function activeCustomer(){return LS.get('customer',{})}
function truckTitle(){const t=activeTruck();return t.vin?`${t.year||''} ${t.make||''} ${t.model||''}`.trim()||t.vin:'NO ACTIVE TRUCK'}
function customerTitle(){const c=activeCustomer();return c.name||'NO CUSTOMER SELECTED'}
function renderAll(){renderHome();renderClock();renderSchedule();renderAlerts();applySettings(false)}
function renderHome(){const t=activeTruck(),c=activeCustomer(); $('homeTruckTitle').textContent=truckTitle(); $('homeTruckMeta').textContent=t.vin?`VIN ${t.vin} • ${t.engine||'ENGINE'} • UNIT ${t.unit||t.unit_number||'—'}`:'VIN • YEAR • MAKE • MODEL • ENGINE'; $('homeCustomerTitle').textContent=customerTitle(); $('homeCustomerMeta').textContent=c.phone||c.email?`${c.phone||''} ${c.email||''}`:'PHONE • EMAIL'; const paid=LS.get('invoices',[]).filter(i=>i.status==='Paid').reduce((a,b)=>a+Number(b.total||0),0); $('todayTotal').textContent=money(paid);}
async function decodeVin(){const vin=$('vin').value.trim().toUpperCase(); if(!vin)return toast('Enter VIN'); $('truckOut').textContent='Decoding VIN...'; try{const res=await fetch(`https://vpic.nhtsa.dot.gov/api/vehicles/DecodeVinValuesExtended/${encodeURIComponent(vin)}?format=json`); const data=await res.json(); const d=data.Results?.[0]||{}; $('truckYear').value=d.ModelYear||''; $('truckMake').value=d.Make||''; $('truckModel').value=d.Model||''; $('truckEngine').value=d.EngineModel||d.EngineManufacturer||''; $('truckOut').textContent=`VIN decoded\nYear: ${d.ModelYear||'—'}\nMake: ${d.Make||'—'}\nModel: ${d.Model||'—'}\nEngine: ${d.EngineModel||d.EngineManufacturer||'—'}`;}catch(e){$('truckOut').textContent='VIN decode failed: '+e.message}}
async function saveTruck(){const t={vin:$('vin').value.trim().toUpperCase(),year:$('truckYear').value.trim(),make:$('truckMake').value.trim(),model:$('truckModel').value.trim(),engine:$('truckEngine').value.trim(),unit_number:$('unitNumber').value.trim(),mileage:$('truckMiles').value.trim(),customer:customerTitle(),created_at:new Date().toISOString()}; LS.set('activeTruck',t); const list=LS.get('trucks',[]); list.unshift(t); LS.set('trucks',list.slice(0,100)); try{await saveRow('active_truck_profiles',{vin:t.vin,year:t.year,make:t.make,model:t.model,engine:t.engine,notes:`Unit ${t.unit_number||''} ${t.mileage||''}`}); toast('Truck saved to Supabase');}catch(e){toast('Truck saved locally: '+e.message)} renderAll();}
function clearTruck(){['vin','truckYear','truckMake','truckModel','truckEngine','unitNumber','truckMiles'].forEach(id=>$(id).value=''); $('truckOut').textContent='';}
async function saveCustomer(){const c={name:$('custName').value.trim(),phone:$('custPhone').value.trim(),email:$('custEmail').value.trim(),address:$('custAddress').value.trim(),notes:$('custNotes').value.trim(),created_at:new Date().toISOString()}; if(!c.name)return toast('Enter customer name'); LS.set('customer',c); const list=LS.get('customers',[]); list.unshift(c); LS.set('customers',list.slice(0,100)); try{await saveRow('customers',c); $('customerOut').textContent='Customer saved to Supabase'; toast('Customer saved to Supabase');}catch(e){$('customerOut').textContent='Customer saved locally only: '+e.message; toast('Customer saved locally only')} renderAll();}
function clearCustomer(){['custName','custPhone','custEmail','custAddress','custNotes'].forEach(id=>$(id).value='');$('customerOut').textContent='';}
function loadCustomerHistory(){const c=activeCustomer(); const jobs=LS.get('history',[]).filter(h=>(h.customer||'')===(c.name||'')); $('customerOut').textContent=jobs.length?jobs.map(j=>`${j.date} • ${j.type} • ${j.truck||''} • ${money(j.total||0)}`).join('\n'):'No local history yet.';}
function getClocks(){return LS.get('clocks',{A:{status:'Ready',elapsed:0},B:{status:'Ready',elapsed:0},C:{status:'Ready',elapsed:0}})} function setClocks(c){LS.set('clocks',c)}
function selectClock(k){activeClock=k;LS.set('activeClock',k);renderClock()}
function currentClock(){const cs=getClocks(); cs[activeClock]??={status:'Ready',elapsed:0}; return cs[activeClock];}
function clockElapsed(c){let e=Number(c.elapsed||0); if(c.status==='Running'&&c.start)e+=now()-c.start; return e;}
function fmt(ms){ms=Math.max(0,ms||0); const s=Math.floor(ms/1000),h=Math.floor(s/3600),m=Math.floor((s%3600)/60),sec=s%60; return [h,m,sec].map(x=>String(x).padStart(2,'0')).join(':')}
function renderClock(){const cs=getClocks(), c=currentClock(), s=settings(); ['A','B','C'].forEach(k=>{$('tab'+k)?.classList.toggle('active',k===activeClock); const chip=$('chip'+k); if(chip){chip.className=''; chip.classList.add(String(cs[k]?.status||'Ready').toLowerCase()); chip.textContent=`${k} ${cs[k]?.status||'Ready'}`;}}); $('clockTitle').textContent='CLOCK '+activeClock; const elapsed=clockElapsed(c), hrs=elapsed/36e5, rate=Number(s.laborRate||135); $('activeClockTime').textContent=fmt(elapsed); $('activeClockMoney').textContent=money(hrs*rate); $('activeClockCustomer').textContent=c.customer||customerTitle(); $('activeClockTruck').textContent=c.truck||truckTitle();}
function clockStartResume(){const cs=getClocks(), c=cs[activeClock]||{elapsed:0}; if(c.status==='Running')return; c.elapsed=clockElapsed(c); c.start=now(); c.status='Running'; c.customer=customerTitle(); c.truck=truckTitle(); cs[activeClock]=c; setClocks(cs); renderClock();}
function clockPause(){const cs=getClocks(), c=cs[activeClock]; if(!c)return; c.elapsed=clockElapsed(c); c.start=null; c.status='Paused'; cs[activeClock]=c; setClocks(cs); renderClock();}
async function clockStop(){const cs=getClocks(), c=cs[activeClock]||{elapsed:0}; c.elapsed=clockElapsed(c); c.start=null; c.status='Stopped'; c.stopped_at=new Date().toISOString(); c.customer=c.customer||customerTitle(); c.truck=c.truck||truckTitle(); const hrs=c.elapsed/36e5, rate=Number(settings().laborRate||135); c.hours=Number(hrs.toFixed(2)); c.total=Number((hrs*rate).toFixed(2)); cs[activeClock]=c; setClocks(cs); try{await saveRow('clock_entries',{clock_name:activeClock,customer:c.customer,truck_vin:activeTruck().vin||'',hours:c.hours,labor_rate:rate,total:c.total,status:'Stopped',stop_time:c.stopped_at});toast('Clock stopped and saved');}catch(e){toast('Clock stopped locally');} renderClock();}
function clearClock(){const cs=getClocks(); cs[activeClock]={status:'Ready',elapsed:0}; setClocks(cs); renderClock();}
function clockToInvoice(){const c=currentClock(), hrs=clockElapsed(c)/36e5; $('iHours').value=hrs.toFixed(2); $('iRate').value=settings().laborRate; show('invoice');}
function startJobWizard(){show('customer'); toast('Start Job: save customer, save truck, pick Clock A/B/C, then START.');}
async function lookupParts(){const q=$('partsQuery').value.trim(); if(!q)return toast('Enter part search'); const box=$('partsResults'); box.innerHTML='<div class="card"><h3>Searching...</h3></div>'; let results=[]; try{const url=settings().backendUrl.replace(/\/$/,'')+'/api/parts?q='+encodeURIComponent(q); const res=await fetch(url); const data=await res.json().catch(()=>null); if(res.ok&&data){results=Array.isArray(data)?data:(data.results||data.parts||[]);} }catch(e){console.warn(e)} const terms=q.toLowerCase().split(/\s+/); const local=localParts.filter(p=>terms.some(t=>p.q.includes(t)||p.name.toLowerCase().includes(t)||p.num.toLowerCase().includes(t))).slice(0,8); results=[...results,...local]; if(!results.length)results=[{name:'No exact match found',num:'UNKNOWN',group:'Search',notes:'Try OEM number, engine family, or use supplier links. Save verified result to job history.'}]; box.innerHTML=results.map((p,i)=>partCard(p,i)).join('');}
function partCard(p,i){const name=p.name||p.description||p.part_name||'Part Result', num=p.num||p.part_number||p.oem_num||p.oem_part_number||'UNKNOWN'; return `<div class="card"><h3>${safe(name)}</h3><p><b>Part #:</b> ${safe(num)}</p><p><b>Group:</b> ${safe(p.group||p.category||'')}</p><p>${safe(p.notes||p.note||p.fitment||'Verify by VIN/ESN before ordering.')}</p><div class="row"><button onclick="addPartToQuote(${i})">Add to Quote</button><button onclick="addPartToInvoice(${i})">Add to Invoice</button></div></div>`}
function currentPartResults(){return [...document.querySelectorAll('#partsResults .card')].map(card=>({name:card.querySelector('h3')?.textContent||'Part',number:(card.textContent.match(/Part #:\s*([^\n]+)/)||[])[1]||''}))}
function addPartToQuote(i){const r=currentPartResults()[i]||{name:'Part',number:''}; $('quoteDesc').value += `\nPart: ${r.name} ${r.number}`; show('quote');}
function addPartToInvoice(i){const r=currentPartResults()[i]||{name:'Part',number:''}; $('invoiceWork').value += `\nPart: ${r.name} ${r.number}`; show('invoice');}
function smartJobParts(){const q=$('partsQuery').value.toLowerCase(); let list=[]; if(q.includes('brake'))list=['Brake shoes','Drums if worn','Hardware kit','Wheel seals','Hub oil','Brake cleaner']; else if(q.includes('water pump'))list=['Water pump','Thermostat','Coolant','Belt','Gasket/O-ring','Hose clamps']; else if(q.includes('clutch'))list=['Clutch kit','Pilot bearing','Clutch brake','Flywheel/resurface','Trans fluid','Rear main inspection']; else list=['Primary part','Gasket/seal kit','Fluids','Hardware','Shop supplies']; $('partsResults').innerHTML=list.map((x,i)=>`<div class="card"><h3>${safe(x)}</h3><p>Smart job item. Verify by VIN/ESN before ordering.</p><div class="row"><button onclick="$('quoteDesc').value+='\\n${safe(x)}';show('quote')">Add to Quote</button><button onclick="$('invoiceWork').value+='\\n${safe(x)}';show('invoice')">Add to Invoice</button></div></div>`).join('');}
function supplier(name){const q=encodeURIComponent($('partsQuery').value||$('quoteDesc').value||'truck parts'); const urls={fleetpride:`https://www.fleetpride.com/search?text=${q}`,napa:`https://www.napaonline.com/en/search?text=${q}`,oreilly:`https://www.oreillyauto.com/search?q=${q}`,truckpro:`https://www.truckpro.com/search?keyword=${q}`,google:`https://www.google.com/search?q=${q}+truck+parts`}; window.open(urls[name]||urls.google,'_blank')}
async function scanImage(e){const f=e.target.files?.[0]; if(!f)return; $('scanPreview').src=URL.createObjectURL(f); $('scanPreview').style.display='block'; $('scanText').value='Reading image...'; try{if(!window.Tesseract)throw new Error('OCR library not loaded'); const res=await Tesseract.recognize(f,'eng'); $('scanText').value=res.data.text||''; parseScanToParts();}catch(err){$('scanText').value='OCR failed: '+err.message}}
function parseScanToParts(){const text=$('scanText').value; const nums=[...new Set((text.match(/\b[A-Z]{1,4}[- ]?\d{3,8}[A-Z0-9-]*\b|\b\d{6,10}\b/gi)||[]).map(x=>x.trim()))]; const prices=[...new Set((text.match(/\$?\d+\.\d{2}/g)||[]))]; $('scanParts').innerHTML=(nums.length?nums:['UNKNOWN']).slice(0,8).map((n,i)=>`<div class="card"><h3>Scanned Part</h3><p><b>Part #:</b> ${safe(n)}</p><p><b>Price:</b> ${safe(prices[i]||prices[0]||'')}</p><div class="row"><button onclick="scanToQuote('${safe(n)}','${safe(prices[i]||prices[0]||'')}')">Add to Quote</button><button onclick="scanToInvoice('${safe(n)}','${safe(prices[i]||prices[0]||'')}')">Add to Invoice</button></div></div>`).join('');}
function scanToQuote(part='',price=''){if(!part){parseScanToParts();part='Scanned receipt parts';} $('quoteDesc').value += `\nScanned: ${part} ${price}`; show('quote');}
function scanToInvoice(part='',price=''){if(!part){parseScanToParts();part='Scanned receipt parts';} $('invoiceWork').value += `\nScanned: ${part} ${price}`; const p=Number(String(price).replace('$',''))||0; if(p) $('iParts').value=Number($('iParts').value||0)+p; show('invoice');}
function clearScan(){['scanText'].forEach(id=>$(id).value='');$('scanParts').innerHTML='';$('scanPreview').style.display='none';}
function quoteTotals(){const h=Number($('qHours').value||0),r=Number($('qRate').value||settings().laborRate),parts=Number($('qParts').value||0),mark=Number($('qMarkup').value||0),svc=Number($('qService').value||0),taxPct=Number($('qTax').value||0); const labor=h*r, partSell=parts*(1+mark/100), sub=labor+partSell+svc, tax=sub*taxPct/100,total=sub+tax; return {h,r,parts,partSell,svc,tax,total,labor,sub}}
function buildQuote(){if(!$('qRate').value)$('qRate').value=settings().laborRate;if(!$('qService').value)$('qService').value=settings().serviceCall;if(!$('qTax').value)$('qTax').value=settings().tax; const t=quoteTotals(), s=settings(); const html=`<div class="docHead"><div><b>${safe(s.shopName)}</b><br>${safe(s.phone)}<br>${safe(s.website)}</div><div><b>QUOTE</b><br>${new Date().toLocaleDateString()}<br>Status: Draft</div></div><div class="docBox"><b>Customer:</b> ${safe(customerTitle())}<br><b>Truck:</b> ${safe(truckTitle())}<br><b>VIN:</b> ${safe(activeTruck().vin||'')}</div><div class="docBox"><b>Work Requested</b><br>${safe($('quoteDesc').value).replace(/\n/g,'<br>')}</div><div class="docBox">Labor: ${t.h} hrs x ${money(t.r)} = ${money(t.labor)}<br>Parts: ${money(t.partSell)}<br>Service Call: ${money(t.svc)}<br>Tax: ${money(t.tax)}</div><div class="docTotal">QUOTE TOTAL: ${money(t.total)}</div>`; $('quoteOut').innerHTML=html; const list=LS.get('quotes',[]); list.unshift({customer:customerTitle(),truck:truckTitle(),vin:activeTruck().vin,total:t.total,status:'Draft',desc:$('quoteDesc').value,date:new Date().toLocaleString()}); LS.set('quotes',list);}
function clearQuote(){['quoteDesc','qHours','qParts','qMarkup','qService'].forEach(id=>$(id).value='');$('quoteOut').innerHTML='';clearCanvas('quoteSig',false)}
function writeProfessionalQuote(){if(!$('quoteDesc').value)return toast('Enter job description'); $('quoteDesc').value=`Professional estimate for ${$('quoteDesc').value.trim()}. Quote includes labor, listed parts/materials, service call when applicable, and standard shop supplies. Final price may vary if additional failed components or hidden damage are found during repair.`; buildQuote();}
function signQuoteMode(){toast('Have customer sign in quote signature box.'); $('quoteSig').scrollIntoView({behavior:'smooth'});}
function sendQuoteSms(){buildQuote(); const text=`Quote from ${settings().shopName}\nCustomer: ${customerTitle()}\nTruck: ${truckTitle()}\n${$('quoteOut').innerText}`; window.location.href=`sms:${activeCustomer().phone||''}?&body=${encodeURIComponent(text.slice(0,1400))}`;}
function approveQuote(){const quotes=LS.get('quotes',[]); if(quotes[0])quotes[0].status='Approved'; LS.set('quotes',quotes); toast('Quote marked approved');}
function quoteToInvoice(){const t=quoteTotals(); $('invoiceWork').value=$('quoteDesc').value; $('iHours').value=t.h; $('iRate').value=t.r; $('iParts').value=t.partSell.toFixed(2); $('iService').value=t.svc; $('iTax').value=$('qTax').value||settings().tax; show('invoice');}
function buildInvoice(copy='customer'){if(!$('iRate').value)$('iRate').value=settings().laborRate;if(!$('iService').value)$('iService').value=settings().serviceCall;if(!$('iTax').value)$('iTax').value=settings().tax; const h=Number($('iHours').value||0),r=Number($('iRate').value||0),parts=Number($('iParts').value||0),svc=Number($('iService').value||0),taxPct=Number($('iTax').value||0),paid=Number($('iPaid').value||0); const labor=h*r,sub=labor+parts+svc,tax=sub*taxPct/100,total=sub+tax,balance=total-paid,s=settings(); const html=`<div class="docHead"><div><b>${safe(s.shopName)}</b><br>${safe(s.owner)}<br>${safe(s.phone)}<br>${safe(s.website)}</div><div><b>INVOICE</b><br>${copy.toUpperCase()} COPY<br>${new Date().toLocaleDateString()}</div></div><div class="docBox"><b>Customer:</b> ${safe(customerTitle())}<br><b>Phone:</b> ${safe(activeCustomer().phone||'')}<br><b>Truck:</b> ${safe(truckTitle())}<br><b>VIN:</b> ${safe(activeTruck().vin||'')}</div><div class="docBox"><b>Work Performed</b><br>${safe($('invoiceWork').value).replace(/\n/g,'<br>')}</div><div class="docBox">Labor: ${h} hrs x ${money(r)} = ${money(labor)}<br>Parts/Materials: ${money(parts)}<br>Service Call: ${money(svc)}<br>Tax: ${money(tax)}<br>Paid: ${money(paid)}</div><div class="docTotal">TOTAL: ${money(total)}<br>BALANCE: ${money(balance)}</div><div class="docBox"><b>Status:</b> ${safe($('paymentStatus').value)}<br><b>Signature:</b> ${canvasHasInk('invoiceSig')?'Captured':'Not signed'}</div>`; $('invoiceOut').innerHTML=copy==='both'?html+'<hr>'+html.replace('CUSTOMER COPY','SHOP COPY'):html; const inv={customer:customerTitle(),truck:truckTitle(),vin:activeTruck().vin,total,balance,status:$('paymentStatus').value,work:$('invoiceWork').value,date:new Date().toLocaleString()}; const list=LS.get('invoices',[]); list.unshift(inv); LS.set('invoices',list); const hist=LS.get('history',[]); hist.unshift({...inv,type:'Invoice'}); LS.set('history',hist); saveRow('invoices',{customer:inv.customer,truck_vin:inv.vin,work_done:inv.work,total:inv.total,status:inv.status,signature:canvasHasInk('invoiceSig')?'captured':'',created_at:new Date().toISOString()}).catch(()=>{}); renderAll();}
function clearInvoice(){['invoiceWork','iHours','iParts','iService','iPaid'].forEach(id=>$(id).value='');$('invoiceOut').innerHTML='';clearCanvas('invoiceSig',false)}
function sendInvoiceSms(){buildInvoice('customer'); const text=`Invoice from ${settings().shopName}\nCustomer: ${customerTitle()}\nTruck: ${truckTitle()}\n${$('invoiceOut').innerText}`; window.location.href=`sms:${activeCustomer().phone||''}?&body=${encodeURIComponent(text.slice(0,1400))}`;}
function readInvoiceAloud(){const text=$('invoiceOut').innerText||'Build invoice first'; if('speechSynthesis'in window){speechSynthesis.cancel(); speechSynthesis.speak(new SpeechSynthesisUtterance(text));}else toast('Read aloud not supported');}
async function saveWorkOrder(){const wo={customer:customerTitle(),truck:truckTitle(),truck_vin:activeTruck().vin||'',complaint:$('complaint').value,diagnosis:$('diagnosis').value,work_done:$('workDone').value,status:'Open',created_at:new Date().toISOString()}; const list=LS.get('workorders',[]); list.unshift(wo); LS.set('workorders',list); try{await saveRow('work_orders',wo);$('workOut').textContent='Work order saved to Supabase';}catch(e){$('workOut').textContent='Work order saved locally: '+e.message}}
function workOrderToInvoice(){$('invoiceWork').value=[ $('complaint').value,$('diagnosis').value,$('workDone').value].filter(Boolean).join('\n'); show('invoice')}
function clearWorkOrder(){['complaint','diagnosis','workDone'].forEach(id=>$(id).value='');$('workOut').textContent=''}
function saveSchedule(){const job={customer:customerTitle(),truck_vin:activeTruck().vin||'',job:$('schedJob').value,date:$('schedDate').value,time:$('schedTime').value,note:$('schedNote').value,status:'Scheduled',created_at:new Date().toISOString()}; const list=LS.get('schedule',[]); list.unshift(job); LS.set('schedule',list); saveRow('schedule',job).catch(()=>{}); renderSchedule();}
function renderSchedule(){const box=$('scheduleOut'); if(!box)return; const list=LS.get('schedule',[]); box.innerHTML=list.length?list.slice(0,20).map(j=>`<div class="card"><h3>${safe(j.date||'No date')} ${safe(j.time||'')}</h3><p>${safe(j.job||'Job')}</p><p>${safe(j.customer||'')} ${safe(j.truck_vin||'')}</p></div>`).join(''):'<div class="card"><h3>No scheduled jobs</h3></div>'}
function clearScheduleForm(){['schedJob','schedNote','schedDate','schedTime'].forEach(id=>$(id).value='')}
function addAlert(){const list=LS.get('alerts',[]); list.unshift({text:$('alertText').value,date:new Date().toLocaleString()}); LS.set('alerts',list); $('alertText').value=''; renderAlerts();}
function renderAlerts(){const box=$('alertsOut'); if(!box)return; const list=LS.get('alerts',[]); box.innerHTML=list.length?list.map(a=>`<div class="card"><h3>Alert</h3><p>${safe(a.text)}</p><p>${safe(a.date)}</p></div>`).join(''):'<div class="card"><h3>No alerts</h3></div>'}
function clearAlerts(){LS.set('alerts',[]);renderAlerts()}
function calcFinance(){const vals=['rent','insurance','electric','fuel','software'].map(id=>Number($(id).value||0)); const overhead=vals.reduce((a,b)=>a+b,0), rate=Number($('financeRate').value||135), revenue=Number($('financeRevenue').value||0), goal=Number($('goal').value||0); const hrs=overhead/rate, goalHrs=goal/rate, profit=revenue-overhead; $('financeOut').innerHTML=`<div class="docHead"><div><b>Shop Finance Plan</b><br>Rolling Wrench Diesel</div><div>${new Date().toLocaleDateString()}</div></div><div class="docBox">Monthly overhead: <b>${money(overhead)}</b><br>Break-even billable hours @ ${money(rate)}/hr: <b>${hrs.toFixed(1)} hrs</b><br>Weekly break-even target: <b>${(hrs/4.33).toFixed(1)} hrs</b></div><div class="docBox">Revenue entered: ${money(revenue)}<br>Projected profit after overhead: <b>${money(profit)}</b><br>Revenue goal: ${money(goal)}<br>Hours for goal: ${goalHrs.toFixed(1)} hrs</div>`;}
function clearFinance(){['fuel','software','goal','financeRevenue'].forEach(id=>$(id).value='');$('financeOut').innerHTML=''}
function saveSettings(){const s={...settings(),theme:$('theme').value,bgStyle:$('bgStyle').value,largeText:$('largeText').checked,simpleMode:$('simpleMode').checked,reducedMotion:$('reducedMotion').checked,backendUrl:$('backendUrl').value,supabaseUrl:$('supabaseUrl').value,supabaseKey:$('supabaseKey').value}; LS.set('settings',s); applySettings(); toast('Settings saved')}
function applySettings(loadFields=true){const s=settings(); document.body.className=''; document.body.classList.add('theme-'+(s.theme||'green')); if(s.largeText)document.body.classList.add('large-text'); if(s.simpleMode)document.body.classList.add('simple-mode'); if(s.reducedMotion)document.body.classList.add('reduced-motion'); if(loadFields&&$('theme')){ $('theme').value=s.theme||'green'; $('bgStyle').value=s.bgStyle||'carbon'; $('largeText').checked=!!s.largeText; $('simpleMode').checked=!!s.simpleMode; $('reducedMotion').checked=!!s.reducedMotion; $('backendUrl').value=s.backendUrl; $('supabaseUrl').value=s.supabaseUrl; $('supabaseKey').value=s.supabaseKey;}}
function resetSettings(){localStorage.removeItem('settings');applySettings();}
async function testBackend(){try{const res=await fetch(settings().backendUrl.replace(/\/$/,'')+'/api/health').catch(()=>fetch(settings().backendUrl)); $('settingsOut').textContent='Backend: '+res.status;}catch(e){$('settingsOut').textContent='Backend error: '+e.message}}
async function testSupabase(){try{const data=await supabaseReq('customers','GET',null,'?select=id&limit=1'); $('settingsOut').textContent='Supabase connected: '+JSON.stringify(data);}catch(e){$('settingsOut').textContent='Supabase error: '+e.message}}
function clearParts(){$('partsQuery').value='';$('partsResults').innerHTML=''}
function voiceTo(id){const SR=window.SpeechRecognition||window.webkitSpeechRecognition; if(!SR)return toast('Voice not supported'); const r=new SR(); r.lang='en-US'; r.onresult=e=>{$(id).value+=(($(id).value?' ':'')+e.results[0][0].transcript);}; r.start();}
function clearCanvas(id,msg=true){const c=$(id); if(!c)return; const ctx=c.getContext('2d'); ctx.clearRect(0,0,c.width,c.height); c.dataset.ink=''; if(msg)toast('Signature cleared')}
function canvasHasInk(id){return $(id)?.dataset.ink==='1'}
function wireCanvas(id){const c=$(id); if(!c)return; const ctx=c.getContext('2d'); ctx.lineCap='round'; ctx.lineJoin='round'; ctx.strokeStyle='#061008'; ctx.lineWidth=4; let down=false,last=null; const pos=e=>{const r=c.getBoundingClientRect(); const p=e.touches?e.touches[0]:e; return {x:(p.clientX-r.left)*(c.width/r.width),y:(p.clientY-r.top)*(c.height/r.height)}}; const start=e=>{e.preventDefault();down=true;last=pos(e);c.dataset.ink='1'}; const move=e=>{if(!down)return; e.preventDefault(); const p=pos(e); ctx.beginPath(); ctx.moveTo(last.x,last.y); ctx.lineTo(p.x,p.y); ctx.stroke(); last=p; c.dataset.ink='1'}; const end=e=>{down=false;last=null}; ['mousedown','touchstart','pointerdown'].forEach(ev=>c.addEventListener(ev,start,{passive:false})); ['mousemove','touchmove','pointermove'].forEach(ev=>c.addEventListener(ev,move,{passive:false})); ['mouseup','mouseleave','touchend','pointerup','pointercancel'].forEach(ev=>c.addEventListener(ev,end));}
function init(){applySettings(); ['quoteSig','invoiceSig'].forEach(wireCanvas); renderAll(); timer=setInterval(renderClock,1000); if('serviceWorker'in navigator)navigator.serviceWorker.register('./service-worker.js').catch(()=>{});}
window.addEventListener('DOMContentLoaded',init);
